Develop to master Apple Home page Clone
bmuhamood/Apple-website-webpage-Clone pull request #1
Opened 2020-07-22 23:26 UTC by pastorp3

2020-07-22 23:47 UTC, pastorp3 commented
- follow github flow

- linters and html validator working weel

- build it with HTML and css

- we use flexbox, gird, gradients

2020-07-23 00:39 UTC, bertil291utn commented
**Status:** Changes requested 🟠  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:

#### Bottom

* [ ] It contains four elements which are links (to other articles or `#`) ([link to page](https://web.archive.org/web/20140301004610/http://www.apple.com/))

![image](https://user-images.githubusercontent.com/24902525/88242045-ac19a300-cc51-11ea-9cfc-12a76d9a2350.png)

#### Background

* [ ] The main content should have an image set as background (as CSS [`background-image`](https://www.w3schools.com/cssref/pr_background-image.asp) or [`background -> url`](https://www.w3schools.com/cssref/css3_pr_background.asp)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_image_requirement.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/building-with-backgrounds-and-gradients))

![image](https://user-images.githubusercontent.com/24902525/88242089-ceabbc00-cc51-11ea-88f9-2b39bf7b960d.png)

### Implementation details

This project consists of building a webpage using images as a background and adding gradients to elements. The goal is to make a clone of old an old version of the [Apple website](https://web.archive.org/web/20140301004610/http://www.apple.com/) webpage.

- [ ]  Background hero should cover al page

![image](https://user-images.githubusercontent.com/24902525/88242246-44b02300-cc52-11ea-9821-96cac34a1209.png)

- [ ] Bottom images should overlap each other 

![image](https://user-images.githubusercontent.com/24902525/88242285-601b2e00-cc52-11ea-8bf5-fc24b7b5f95c.png)

- [ ] Please add margin-bottom for the footer

![image](https://user-images.githubusercontent.com/24902525/88242364-880a9180-cc52-11ea-831d-79e3162e2450.png)

### Summary

- Work on the details of the implementation remember your approach should be clone of the original one

<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-23 01:21 UTC, pastorp3 commented
- add a link to the images

- change the images to a background image

- main background hero is already with background-size: cover; 

- add space between each image

- add a margin to the footer

2020-07-23 01:44 UTC, pastorp3 commented
there is something wrong with the live server it cut the bottom images but the original file its display in the right mode

2020-07-23 04:13 UTC, kitpao requested changes
# 👋 Hello Team,

🙌 Nice work with your webpage 👍 You have mastered the main concepts and your page looks very similar to the original, and just missing some little details ⬇️ 

- [ ] **[MANDATORY]** To eliminate that white space that surrounds your page as the previous TSE required, just take out the margin in the body

### ♻️ Status: Your project requires some additional changes ♻️

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__ 


___
**PD.** About the **cutten images** in the bottom, the reason that you have a "bug" there is because you put a height to your main tag and the body is taking automatically that height because your main is the only direct child of the body according to your html

--> So there are elements "outside" the main. The browser doesn't knows how to handle it and sometimes shows it and sometimes it doesn't, here is a screenshot of the limits the browser is taking, and it's the same place it is cutting your images:
![image](https://user-images.githubusercontent.com/53256139/88250824-5b647300-cc6e-11ea-91e7-cb54360e624e.png)

**OPTIONAL SUGGESTION:** Next time try to use a single `<element>` for each big section, don't be afraid of using as many containers as you need, one proposal for this project could be: 
```
  <body>
      <main>
          <div class= "hero-image">
              <nav>
              </nav>
          </div>
          <div class= "grid">
          </div>
      </main>
      <footer>
      </footer>
  </body>
```
#### Don't forget the requirements below ⬇️ 

.

2020-07-23 04:13 UTC, kitpao commented on css/main.css
> +  background-color: #ccc;
- [ ] This background-color is unnecessary since you already have your background image, please remove it

2020-07-23 04:13 UTC, kitpao commented on css/main.css
> +  object-fit: cover;
- [ ] This object-fit is not necessary since you are already using the background-size, please remove it

2020-07-23 04:13 UTC, kitpao commented on index.html
> +                    <a class="a4" href="#"></a>
- [ ] **[MANDATORY** Use are missing the background-position property to display this images in the center:
![image](https://user-images.githubusercontent.com/53256139/88250139-44248600-cc6c-11ea-90b3-5c01bcfedca4.png)

2020-07-23 06:26 UTC, pastorp3 commented
- change the size of the grid box now it displays correctly

- delete the unnecessary css rules

- center grid images

2020-07-23 06:54 UTC, kitpao approved these changes
# 👋 Ji @pastorp3 and @bmuhamood 

💯 Excellent job guys!! You did all required changes, and pretty good approach the one of adding height to your grid to solve the previous problem 🥇 👍

### 👏 Your project has been approved 👏
### 🚀 You may merge to master and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-23 07:42 UTC, merged

2020-07-23 07:42 UTC, bmuhamood commented
Appreciated a lot for the professional code review and really helped us understand the chapter well

2020-07-23 12:23 UTC, kitpao commented
Your welcome guys